In [1]:
import numpy as np

In [2]:
arr = np.array([10, 20, 30, 40, 50])


In [3]:
print(arr)

[10 20 30 40 50]


In [4]:
np.array([1, 2, 3])


array([1, 2, 3])

In [5]:
np.array([[1, 2, 3], [4, 5, 6]])


array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [7]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [8]:
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [11]:
arr.size

12

In [12]:
arr = np.array([[1,2,3],[4,5,6]])


In [13]:
print(arr.ndim) 

2


In [14]:
print(arr.shape)

(2, 3)


In [15]:
print(arr.size)  

6


In [16]:
print(arr.dtype)

int64


In [17]:
arr = np.array([10, 20, 30, 40, 50])


In [18]:
print(arr[0])      # First element


10


In [19]:
print(arr[-1])     # Last element


50


In [20]:
print(arr[1:4])    # Slice 1 to 3


[20 30 40]
